[config]

[templates]

[templates.rofi]
input_path = "~/.config/noctalia/templates/rofi.rasi"
output_path = "~/.config/rofi/matugen/colors.rasi"

[templates.nvim-base16]
input_path = "~/.config/nvim/lua/matugen-template.lua"
output_path = "~/.config/nvim/lua/matugen.lua"
post_hook = 'pkill -SIGUSR1 nvim'
